name: Run python tests

on:
  push:
    branches: [ "homework2" ]
  pull_request:
    branches: [ "homework2" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.11" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: abatilo/actions-poetry@v2
      - name: Install dependencies with poetry
        run: poetry install
      - name: Run tests
        run: poetry run python -m pytest -vv --strict --showlocals --cov=src/